# Generated by Django 4.2.2 on 2023-07-03 06:54

import diarys.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(validators=[diarys.validators.validate_no_hash]),
        ),
        migrations.AlterField(
            model_name='page',
            name='dt_created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='feeling',
            field=models.CharField(max_length=50, validators=[diarys.validators.validate_no_numbers, diarys.validators.validate_no_hash]),
        ),
        migrations.AlterField(
            model_name='page',
            name='score',
            field=models.IntegerField(validators=[diarys.validators.validate_score]),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=100, validators=[diarys.validators.validate_no_hash]),
        ),
    ]
